---
- name: setup python
  hosts: all
  gather_facts: false
  tasks:
  - name: update apt repo
    apt: update_cache=yes force_apt_get=yes cache_valid_timem=3600
    become: true
  - name: upgrade apt pack
    apt: upgrade=yes force_apt_get=yes
    become: true
  - name: Install python pip
    apt: name{{ item }} update_cache=true state=present force_apt_get=yes
    with_items:
    - python-pip
    - python3-pip
    become: true
  - name: Install Pythoon packages
    pip: name{{ item }}
    with_items:
    - psycopg2-binary
    become: true
